version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yummi_app
    working_dir: /var/www/src/laravel
    volumes:
      - ./src/laravel:/var/www/src/laravel
    depends_on:
      - mysql
    networks:
      - yummi

  nginx:
    image: nginx:alpine
    container_name: yummi_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/laravel:/var/www/src/laravel
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - yummi

  mysql:
    image: mysql:8.0
    container_name: yummi_mysql
    restart: always
    environment:
      MYSQL_DATABASE: yummi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - yummi

  node:
    image: node:20-alpine
    container_name: yummi_node
    working_dir: /var/www/src/laravel
    volumes:
      - ./src/laravel:/var/www/src/laravel
    tty: true
    networks:
      - yummi

volumes:
  mysql_data:

networks:
  yummi:
    driver: bridge

